In [10]:
import numpy as np

# LU decomposition for tridiagonal matrixes
<br>
If we have a Matrix With the form:

$$ \begin{bmatrix} b_1&c_1&0&\dots&\dots&\\
a_2&b_2&c_2&0&\dots&\\
0&\ddots&\ddots&\ddots&0&\\
&0&\ddots&\ddots&\ddots&0\\
&&0&a_{n-1}&b_{n-1}&c_{n-1}\\
&&&0&a_n&b_n\\
\end{bmatrix}$$

<br> It can be decomposed in two matrixes (M= L*U):
$$ \begin{bmatrix} 1&0&0&\dots&\dots&\\
l_2&1&0&0&\dots&\\
0&\ddots&\ddots&\ddots&0&\\
&0&\ddots&\ddots&\ddots&0\\
&&0&l_{n-1}&1&0\\
&&&0&l_n&1\\
\end{bmatrix}
\begin{bmatrix} v_1&c_1&0&\dots&\dots&\\
0&v_2&c_2&0&\dots&\\
0&\ddots&\ddots&\ddots&0&\\
&0&\ddots&\ddots&\ddots&0\\
&&0&0&v_{n-1}&c_{n-1}\\
&&&0&0&v_n\\
\end{bmatrix}$$

where:
$$ b_1=v_1 \Longrightarrow v_1=b_1$$
$$a_k=l_kv_{k-1}\Longrightarrow l_k=\frac{a_k}{v_{k-1}}$$
$$b_k=l_kc_{k-1}+v{k}\Longrightarrow v_k=b_k-l_kc{k-1}$$
$$k=2,.....,n$$



In [11]:
# entry data
lowerDIAG=[1,2,3]
upperDIAG=[3,2,4]
mainDIAG=4
b=[1,2,3,4]

In [12]:
# LU factorization for tridiagonal matrix

def LUt(m):

    #extract the 3 diagonals of the matriz in 3 vectors
    #b=center diagonal|a=lower diagonal|c=uper diagonal
    b=np.diag(m)
    a=np.diag(m,k=-1)
    c=np.diag(m,k=1)
    #Creation of LU matrixes diagonals
    v=np.array([b[0]])
    l=np.array([])
    for i in range (1,len(b)):
        l=np.append(l,a[i-1]/v[i-1])
        v=np.append(v,b[i]-np.dot(l[i-1],c[i-1]))
        
    #"mounting" the diagonals into the LU matrixes
    L=np.identity(len(m))+np.diag(l,k=-1)
    U=np.diag(v)+np.diag(c,k=1)
    
    return L,U

      

m=np.identity(mainDIAG)+np.diag(lowerDIAG,k=-1)+np.diag(upperDIAG,k=1)
L,U=LUt(m)
print("matrix L: \n")
print(L)
print("\n matrix U: \n")
print(U)


matrix L: 

[[ 1.  0.  0.  0.]
 [ 1.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  0.  1.  1.]]

 matrix U: 

[[ 1.  3.  0.  0.]
 [ 0. -2.  2.  0.]
 [ 0.  0.  3.  4.]
 [ 0.  0.  0. -3.]]


# Solving a Matrix equation Mx=b

In [13]:
def LUsolver(L,U,b):
    #  LUx=b ->Ly=b->Ux=y
    #Find y
    y=np.zeros(len(b))
    x=np.zeros(len(b))
    y[0]=b[0]
    for i in range(1,len(L)):
        y[i]=b[i]
        for j in range(i):
            y[i]-= np.dot(y[j],L[i,j])
    
    #Find x    
    for i in range(len(U)-1,-1,-1):
        x[i]=y[i]
        for j in range(i+1,len(U)):
            x[i]-=np.dot(x[j],U[i,j])
        x[i]/=U[i,i]
    
    return x


res=LUsolver(L,U,b)
np.set_printoptions(precision=3)
print("\nSolucion:")
print(res)


Solucion:
[-1.5    0.833  1.333 -0.   ]
