In [4]:
import numpy as np
a=np.array([[1,2,0,3],[2,5,6,0],[0,6,9,5],[3,0,5,1]])

In [5]:
def QR(m):
    # QR factorization with Gram-Schmidt
    R=.0*m
    #create function Q
    for i in range (len(m)):
        a=m[:,i]
        u=a
        if i==0:
            e=u/np.sqrt(np.dot(u,u))
            Q=np.vstack(e)
        else:            
            for j in np.transpose(Q):
                u=u-np.dot(a,j)*j
            e=u/np.sqrt(np.dot(u,u))
            Q=np.column_stack((Q,e))
    
    # create R
    for k in range( len(np.transpose(Q))):
        for z in range(k,len(np.transpose(m))):
            R[k,z]=np.dot(m[:,z],Q[:,k])

                      
    return Q,R
                
                


#print(np.linalg.qr(a))
q,r=QR(a)
print("Q:")
print(q)
print("\nR:")
print(r)
print("\nQ*R:")
print(np.dot(q,r))

Q:
[[ 0.2673  0.1545 -0.6785  0.6666]
 [ 0.5345  0.4442 -0.3206 -0.6436]
 [ 0.      0.8111  0.4933  0.3141]
 [ 0.8018 -0.3476  0.4399  0.2069]]

R:
[[3.7417 3.2071 7.2161 1.6036]
 [0.     7.3969 8.2274 4.1716]
 [0.     0.     4.7158 0.8709]
 [0.     0.     0.     3.7773]]

Q*R:
[[ 1.  2.  0.  3.]
 [ 2.  5.  6.  0.]
 [ 0.  6.  9.  5.]
 [ 3. -0.  5.  1.]]


Let $ M_0=Q_0R_0$ <br/> A matrix with the form: $M_1=R_0Q_0$ will slowlly tend to a diagonalized matriz with the same eigenvalues as $M_0$<br/>
As such,  we can repeat the process iteratively:
$$ M_i=R_{i-1}Q_{i-1}$$


In convergent cases: 
$$ \left\{\begin{array}{l}i\rightarrow+\infty \\M_i \rightarrow diagonalized-eigenvalue-matrix \end{array}\right. $$


In the same iteration, let Vec be the eigenvector matrix:
$$ Vec= \Pi_{j=0}^{i-1}Q_j$$


In [6]:
def QRalg(m,p):
    vec=0
    a=m
    for i in range (p):
        q,r=QR(a)
        #a -> matrix that converges to diagonal with each iteration
        a=np.dot(r,q)
        #vec -> matrix that converges to eigenvector matrix (eigenvector=column) with each iteration
        if isinstance(vec, int):
            vec=q
        else:
            vec=np.dot(vec,q)
    return(np.diag(a),vec)
np.set_printoptions(precision=4,suppress=True)
val,vec=QRalg(a,100)
print("\nEIGENVALUES:")
print(val)
print("\nEIGENVECTORS:")
print(vec)

#Verificação
#np.linalg.eig(a)
    


EIGENVALUES:
[14.8648 -4.4049  3.1494  2.3907]

EIGENVECTORS:
[[ 0.1415 -0.5044  0.3418  0.7802]
 [ 0.5084  0.3706 -0.647   0.4308]
 [ 0.7888 -0.4127  0.0856 -0.4474]
 [ 0.3151  0.6618  0.6762  0.0745]]
